[local]
localhost

[mongodb]
mongodb.daws-90.online

[redis]
redis.daws-90.online

[mysql]
mysql.daws-90.online

[rabbitmq]
rabbitmq.daws-90.online

[catalogue]
catalogue.daws-90.online

[user]
user.daws-90.online

[cart]
cart.daws-90.online

[shipping]
shipping.daws-90.online

[payment]
payment.daws-90.online

[frontend]
frontend.daws-90.online

[private-key-demo]
172.31.37.172