- name: nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml

- name: application set unzip
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: copy service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

- name: enable and restart user
  service:
    name: user
    state: restarted
    enabled: yes