- name: install maven & mysql
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
  - maven
  - mysql

- name: download dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app